# Generated by Django 5.1.2 on 2024-10-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0001_initial'),
        ('train', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Station',
        ),
        migrations.AlterField(
            model_name='train',
            name='stops',
            field=models.ManyToManyField(to='station.station'),
        ),
    ]
