# Generated by Django 5.1.2 on 2024-10-16 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0001_initial'),
        ('train', '0002_delete_station_alter_train_stops'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='stops',
        ),
        migrations.CreateModel(
            name='TrainStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_time', models.DateTimeField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='station.station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='train.train')),
            ],
            options={
                'ordering': ['stop_time'],
            },
        ),
    ]
