# Generated by Django 5.1.2 on 2024-10-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='fare',
            field=models.FloatField(default=0.0),
        ),
    ]
