# Generated by Django 5.1.2 on 2024-10-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_alter_ticket_fare'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
